FROM node:20-bookworm-slim

WORKDIR /app/dashboard

COPY dashboard/package*.json ./
RUN npm ci --legacy-peer-deps

COPY dashboard ./

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0

ENV NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV GEMINI_API_KEY
ENV GEMINI_MODEL
ENV NEXT_PUBLIC_APP_URL
ENV SUPABASE_SERVICE_ROLE_KEY
ENV GOOGLE_CSE_API_KEY
ENV GOOGLE_CSE_ID
ENV CF_WORKER_URL

RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "npm run start -- -H 0.0.0.0 -p ${PORT:-3000}"]
